ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("to_do_list.urls", namespace="to_do_list"))
]

to_do_list/urls.py
from django.urls import path

from to_do_list.views import *

urlpatterns = [
    path("", ToDoListView.as_view(), name="ToDoList"),
    path("creat-task/", CreateTaskView.as_view(), name="create-task"),
    path("update-task/<int:pk>/", UpdateTaskView.as_view(), name="update-task"),
    path("delete-task/<int:pk>/", DeleteTaskView.as_view(), name="delete-task"),
    path("task-status/<int:pk>/", change_task_status, name="change-task-status"),
    path("tags/", TagListView.as_view(), name="Tags"),
    path("creat-tag/", CreateTagView.as_view(), name="create-tag"),
    path("update-tag/<int:pk>/", UpdateTagView.as_view(), name="update-tag"),
    path("delete-tag/<int:pk>/", DeleteTagView.as_view(), name="delete-tag"),

]

app_name = "to_do_list"

to_do_list/models.py
from django.db import models


class Tags(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.tag}"


class Task(models.Model):
    content = models.TextField()
    time_creation = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tags)

    class Meta:
        ordering = ["status", "time_creation"]

to_do_list/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from to_do_list.models import Task, Tags


class ToDoListView(generic.ListView):
    model = Task
    template_name = "to_do_list/home.html"
    paginate_by = 5


class CreateTaskView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:ToDoList")
    template_name = "to_do_list/form_task.html"


class UpdateTaskView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:ToDoList")
    template_name = "to_do_list/form_task.html"


class DeleteTaskView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("to_do_list:ToDoList")


def change_task_status(request, pk):
    task = Task.objects.get(id=pk)
    task.status = False if task.status else True
    task.save()
    return HttpResponseRedirect(reverse_lazy("to_do_list:ToDoList"))


class TagListView(generic.ListView):
    model = Tags
    template_name = "to_do_list/tags.html"
    paginate_by = 5


class CreateTagView(generic.CreateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:Tags")
    template_name = "to_do_list/form_tags.html"


class UpdateTagView(generic.UpdateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:Tags")
    template_name = "to_do_list/form_tags.html"


class DeleteTagView(generic.DeleteView):
    model = Tags
    success_url = reverse_lazy("to_do_list:Tags")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body style="background: darkseagreen">
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
              <ul class="sidebar-nav list-group" style="margin-top: 80px">
                <li class="list-group-item"><a href="{% url 'to_do_list:ToDoList' %}">Home</a></li>
                <li class="list-group-item"><a href="{% url 'to_do_list:Tags' %}">Tags</a></li>
              </ul>
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}

             {% if is_paginated %}
                <ul class="pagination">
                  {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
                    </li>
                  {% endif %}
                    <li class="page-item active">
                      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
                    </li>
                  {% if page_obj.has_next %}
                    <li class="page-item">
                      <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
                    </li>
                  {% endif %}
                </ul>
            {% endif %}

            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/to_do_list/form_tags.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="{{ object|yesno:"Update,Create" }}">
  </form>
{% endblock %}

templates/to_do_list/form_task.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="{{ object|yesno:"Update,Create" }}">
  </form>
{% endblock %}

templates/to_do_list/home.html
{% extends 'base.html' %}

{% block content %}
  <h1 style="margin-top: 30px; margin-left: 500px">
    TODO list
    <a class="btn btn-primary" style="float: right" href="{% url 'to_do_list:create-task' %}">
      Add task
    </a>
  </h1>
  <ul style="list-style: none">
  {% for task in task_list %}
    <li style="background: bisque; border: aqua solid 5px; margin-bottom: 15px; padding-bottom: 30px; padding-left: 30px">

    <div style="display: flex; margin-top: 30px">
      <div>
        <strong>{{ task.content }}</strong>
      </div>
      <div>
       {% if task.status %}
         <p style="color: green; margin-left: 30px">Done</p>
       {% else %}
          <p style="color: red; margin-left: 30px">Not done</p>
       {% endif %}
       </div>
    </div>

      {% if task.status %}
        <a class="btn btn-info" style="float: right; margin-right: 30px" href="{% url 'to_do_list:change-task-status' pk=task.pk %}">Undo</a>
      {% else %}
        <a class="btn btn-success" style="float: right; margin-right: 30px" href="{% url 'to_do_list:change-task-status' pk=task.pk %}">Complete</a>
      {% endif %}

    <div>
      <p>Tags:
        {% for tag in task.tags.all %}
          {{ tag }}
        {% endfor %}
      </p>
    </div>

    <div>

      <div>
         Creation time: {{ task.time_creation }}
      <div>

      <div>
         Deadline: {{ task.deadline }}
      <div>
    <div style="display: flex">
      <div>
        <a class="btn btn-primary" href="{% url 'to_do_list:update-task' pk=task.pk %}">Update</a>
      </div>
      <div>
        <a class="btn btn-danger" href="{% url 'to_do_list:delete-task' pk=task.pk %}">Delete</a>
      </div>
    </div>
    </div>
      </div>
      </div>
    </li>
  {% endfor %}
  </ul>

{% endblock %}

templates/to_do_list/tags.html
{% extends 'base.html' %}

{% block content %}
  <div style="margin-top: 50px; padding-left: 50px; background: whitesmoke">
  <h1 style="padding-bottom: 30px">
    Tags
    <a href="{% url 'to_do_list:create-tag' %}" class="btn btn-primary" style="float: right; margin: 30px">
      Add
    </a>
  </h1>
  {% if tags_list %}
    <table class="table">
    <tr>
        <th>ID</th>
        <th>Tag</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
  {% for tag in tags_list %}
     <tr>
          <td>
              {{ tag.id }}
          </td>
          <td>
              {{ tag.tag }}
          </td>
          <td>
              <a href="{% url 'to_do_list:update-tag' pk=tag.id %}" class="btn btn-success">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'to_do_list:delete-tag' pk=tag.id %}" class="btn btn-danger">
                Delete
              </a>
            </td>
        </tr>
  {% endfor %}
     </table>
  </div>
  {% endif %}
{% endblock %}

templates/to_do_list/tags_confirm_delete.html
<{% extends 'base.html' %}>

{% block content %}
  <div style="border: red solid 5px; width: 600px; margin: 300px 0 0 300px">
  <h1>Do you want to delete this tag?</h1>
   <div style="display: flex; padding-left: 200px">
   <div style="margin-right: 20px;">
  <form action="" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Delete">
  </form>
   </div>
   <div>
     <a class="btn btn-primary" href="{% url 'to_do_list:Tags' %}">Return Back</a>
   </div>
   </div>
  </div>
{% endblock %}

templates/to_do_list/task_confirm_delete.html
<{% extends 'base.html' %}>

{% block content %}
  <div style="border: red solid 5px; width: 600px; margin: 300px 0 0 300px">
  <h1>Do you want to delete this task?</h1>
   <div style="display: flex; padding-left: 200px">
   <div style="margin-right: 20px;">
  <form action="" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Delete">
  </form>
   </div>
   <div>
     <a class="btn btn-primary" href="{% url 'to_do_list:ToDoList' %}">Return Back</a>
   </div>
   </div>
  </div>
{% endblock %}